---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ansibleinstancegroups.tower.ansible.com
spec:
  group: tower.ansible.com
  names:
    kind: AnsibleInstanceGroup
    listKind: AnsibleInstanceGroupList
    plural: ansibleinstancegroups
    singular: ansibleinstancegroup
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: (Tech Preview) AnsibleInstanceGroup is the Schema for the ansibleinstancegroups API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              name:
                type: string
                description: The name of the Instance Group
              credential_name:
                type: string
                description: 'Credential name, ID, or named URL to authenticate with Kubernetes or OpenShift.
                  Must be of type “OpenShift or Kubernetes API Bearer Token”. Only for ContainerGroup.'
              is_container_group:
                type: boolean
                default: false
                description: Whether this is a ContainerGroup (if true) or an InstanceGroup (if false). Defaults to false.
              max_concurrent_jobs:
                type: integer
                description: Maximum number of concurrent jobs to run on this group. Zero means no limit.
              max_forks:
                type: integer
                description: Max forks to execute on this group. Zero means no limit.
              pod_spec_override:
                type: string
                description: A custom Kubernetes or OpenShift Pod specification. Only for ContainerGroup.
              policy_instance_percentage:
                type: integer
                description: The percentage of instances to use for this instance group. Only for InstanceGroup.
              policy_instance_minimum:
                type: integer
                description: The minimum number of instances to use for this instance group. Only for InstanceGroup.
              instance_list:
                type: array
                items:
                  type: string
                description: A list of instance names, IDs, or named URLs associated with this instance_group. Only for InstanceGroup.
              runner_image:
                type: string
                description: Runner image used when running jobs
              runner_version:
                type: string
                description: Runner image version used when running jobs
              runner_pull_policy:
                type: string
                description: Runner image pull policy used when running jobs
              connection_secret:
                type: string
                description: |
                  A k8s secret that contains an access token for AWX. To create an access token see these docs: https://docs.ansible.com/automation-controller/4.1.0/html/userguide/applications_auth.html#add-tokens.
            required:
            - connection_secret
            - name
            description: Spec defines the definition of the Ansible Instance Group
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of AnsibleInstanceGroup
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
